---
dependency:
  name: galaxy
driver:
  name: docker
log: true
platforms:
  - name: centos8
    image: centos:8
    privileged: true
    dockerfile: Dockerfile
    # needed for systemd stuff
    command: /sbin/init
    capabilities:
      - SYS_ADMIN

provisioner:
  name: ansible
  inventory:
    host_vars:
      centos8:
        ansible_user: root
      ubuntu:
        ansible_user: root

verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
