---
- name: Install Vagrant on Centos 8/RHEL 8
  include_tasks: centos8.yml
  when: ((ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux') and
         ansible_distribution_version|int == 8)


- name: Install Vagrant on Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
