---
- name: Install Vagrant on Centos 8/RHEL 8
  include_tasks: centos8.yml
  when: ((ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux') and
         ansible_distribution_version|int == 8)


- name: Install Vagrant on Fedora
  include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"


- name: Install Vagrant on Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"


- name: Clone my vagrant repo
  git:
    repo=https://github.com/slawqo/vagrant
    version=master
    dest=/home/{{ ansible_user }}/vagrant
