#!/bin/bash

# Script checks if any offlineimap instance is running and returns 1 if it is
# True

/usr/bin/ps aux | grep -v grep | /usr/bin/grep -q /usr/bin/offlineimap

if [ $? -eq 0 ]; then
    echo 1
else
    echo 0
fi
