---
- name: Instal libvirt on Fedora
  include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Instal libvirt on Centos
  include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Instal libvirt on Arch Linux
  include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"

- name: Ensure group "libvirt" exists
  become: yes
  become_method: sudo
  group:
      name: libvirt
      state: present

- name: Adding existing user {{ ansible_user_id }} to group libvirt
  user:
      name: "{{ ansible_user_id }}"
      groups: libvirt
      append: yes
  become: yes
  become_method: sudo


- name: Ensure libvirt is running
  systemd:
      name: libvirtd
      state: started
  become: yes
  become_method: sudo
