#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#

export LC_TYPE=
export LANG=en_US.UTF-8

export EDITOR="vim"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Settings for fzf searching tool
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--height 40% --reverse --border'

# Make ssh-agent forwarding working always inside tmux
if [[ -S "$SSH_AUTH_SOCK" && ! -h "$SSH_AUTH_SOCK" ]]; then
    ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock;
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock;


# Special function to source devstack's openrc file in zsh
function sourceopenrc {
    DEVSTACK_DIR="/opt/stack/devstack"
    export BASH_SOURCE="$DEVSTACK_DIR/openrc"
    pushd $DEVSTACK_DIR >/dev/null
    eval $(bash -c "source <(sed '/echo/d' openrc) $1 $2;env|sed -n '/OS_/ { s/^/export /;p}'")
    unset BASH_SOURCE
    popd >/dev/null
}

alias git_clean_merged_branches='git branch --merged | egrep -v "(^\*|master|stable)" | xargs git branch -d'
