---
- name: Install podman package
  become: yes
  become_method: sudo
  package:
      name: podman
      state: present

- name: Install podman-compose package
  become: yes
  become_method: sudo
  package:
      name: podman-compose
      state: present
