---
- name: Create /opt/stack directory
  become: yes
  become_method: sudo
  file:
    path=/opt/stack
    state=directory
    mode=0755
    owner={{ ansible_user }}


- name: Clone neutron
  git:
      repo=https://github.com/openstack/neutron.git
      dest=/opt/stack/neutron
      version={{ neutron_branch }}


