---
- name: Instal kerberos on RHEL
  include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Instal kerberos on Arch Linux
  include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"

- name: Copy krb5 config file
  template:
      src=templates/krb5.conf.j2
      dest=/etc/krb5.conf
  become: yes
  become_method: sudo

- name: Copy sssd config file
  template:
      src=templates/sssd.conf.j2
      dest=/etc/sssd/conf.d/{{ default_ipa_realm_domain }}.conf
  become: yes
  become_method: sudo
