---
- name: Clone tripleo-repos repository
  git:
    repo=https://github.com/openstack/tripleo-repos.git
    version=master
    dest={{ ansible_env.HOME }}/tripleo-repos
    accept_hostkey=True
    force=yes

- name: Install python3-requests
  become: yes
  become_method: sudo
  package:
      name: python3-requests
      state: latest

- name: Install tripleo-repos
  shell: python3 setup.py install
  args:
    chdir: "{{ ansible_env.HOME }}/tripleo-repos"
  become: yes
  become_method: sudo

- name: Enable TripleO repositories
  shell: /usr/local/bin/tripleo-repos current
  become: yes
  become_method: sudo

- name: Install python-tripleoclient
  become: yes
  become_method: sudo
  package:
    name: ["python3-tripleoclient"]

- name: Create standalone script
  template:
    src=standalone.sh.j2
    dest="{{ ansible_env.HOME }}/standalone.sh"
  when: iface is defined

- name: Create OS bootstrap script
  template:
    src=os_bootstrap.sh.j2
    dest="{{ ansible_env.HOME }}/os_bootstrap.sh"
