---
- name: Set SSL certs path on Fedora
  set_fact:
      ssl_certs_path="/etc/ssl/certs/ca-bundle.crt"
  when: ansible_distribution == 'Fedora'


- name: Set SSL certs path on Mac OS
  set_fact:
      ssl_certs_path="/usr/local/etc/openssl/cert.pem"
  when: ansible_distribution == 'MacOSX'


- name: Synchronize weechat files
  synchronize:
      src: "files/weechat/"
      dest: "{{ ansible_env.HOME }}/.weechat/"
      use_ssh_args: yes


- name: Create IRC logs place
  file:
      path: "{{ ansible_env.HOME }}/.irc_logs"
      state: directory


- name: Create weechat irc logs link
  file:
      src: "{{ ansible_env.HOME }}/.irc_logs"
      dest: "{{ ansible_env.HOME }}/.weechat/logs"
      state: link


- name: Create weechat irc config file
  template:
      src=weechat_irc_conf.j2
      dest="{{ ansible_env.HOME }}/.weechat/irc.conf"


- name: Create weechat sec config file
  template:
      src=weechat_sec_conf.j2
      dest="{{ ansible_env.HOME }}/.weechat/sec.conf"


- name: Ensure config dir exists
  file:
      path: "{{ ansible_env.HOME }}/.config"
      state: directory


- name: Ensure gertty config dir exists
  file:
      path: "{{ ansible_env.HOME }}/.config/gertty"
      state: directory


- name: Create gertty config file
  template:
      src=gertty.yaml.j2
      dest="{{ ansible_env.HOME }}/.config/gertty/gertty.yaml"
      mode=0600


- name: Ensure tlp config dir exists
  become: true
  become_method: sudo
  file:
      path: "/etc/tlp.d"
      state: directory


- name: Copy tlp config
  become: true
  become_method: sudo
  copy:
      src: "files/tlp/01-custom.conf"
      dest: "/etc/tlp.d/01-custom.conf"


- name: Copy intel-undervolt config
  become: true
  become_method: sudo
  copy:
      src: "files/intel-undervolt.conf"
      dest: "/etc/intel-undervolt.conf"
  notify:
    - "apply intel-undervolt"
