---
- name: Synchronize mutt files
  synchronize:
      src: "files/mutt/"
      dest: "{{ ansible_env.HOME }}/.mutt/"
      use_ssh_args: yes


- name: Copy work mutt config
  copy:
      src: "files/muttrc_work"
      dest: "{{ ansible_env.HOME }}/.muttrc"


- name: Copy private mutt config
  copy:
      src: "files/muttrc_private"
      dest: "{{ ansible_env.HOME }}/.muttrc_kaplonskipl"


- name: Ensure mails directory exists
  file:
      path: '{{ ansible_env.HOME }}/.mails'
      state: directory

- name: Ensure mail aliases file exists
  file:
      path: '{{ ansible_env.HOME }}/.mails/aliases'
      state: file


- name: Set SSL certs path on Fedora
  set_fact:
      ssl_certs_path="/etc/ssl/certs/ca-bundle.crt"
  when: ansible_distribution == 'Fedora'


- name: Set SSL certs path on Mac OS
  set_fact:
      ssl_certs_path="/usr/local/etc/openssl/cert.pem"
  when: ansible_distribution == 'MacOSX'


- name: Create offlineimaprc
  template:
      src=offlineimaprc.j2
      dest="{{ ansible_env.HOME }}/.offlineimaprc"


- name: Synchronize weechat files
  synchronize:
      src: "files/weechat/"
      dest: "{{ ansible_env.HOME }}/.weechat/"
      use_ssh_args: yes


- name: Create IRC logs place
  file:
      path: "{{ ansible_env.HOME }}/.irc_logs"
      state: directory


- name: Create weechat irc logs link
  file:
      src: "{{ ansible_env.HOME }}/.irc_logs"
      dest: "{{ ansible_env.HOME }}/.weechat/logs"
      state: link


- name: Create weechat irc config file
  template:
      src=weechat_irc_conf.j2
      dest="{{ ansible_env.HOME }}/.weechat/irc.conf"


- name: Create weechat sec config file
  template:
      src=weechat_sec_conf.j2
      dest="{{ ansible_env.HOME }}/.weechat/sec.conf"


- name: Ensure config dir exists
  file:
      path: "{{ ansible_env.HOME }}/.config"
      state: directory


- name: Ensure gertty config dir exists
  file:
      path: "{{ ansible_env.HOME }}/.config/gertty"
      state: directory


- name: Create gertty config file
  template:
      src=gertty.yaml.j2
      dest="{{ ansible_env.HOME }}/.config/gertty/gertty.yaml"
      mode=0600

