#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export EDITOR="vim"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Functions to call trello-sprint tool
trello_tool_path="/Users/skaplons/dev/trello-sprint/trello_sprint"
function trello_sprint() {
    board=$1
    if [ ! -n "$board" ]; then
        board="DFG-Networking-vNES Squad"
    fi
    python3 $trello_tool_path/main.py --config $trello_tool_path/auth.conf $board
}

function trello_sprint_members() {
    board=$1
    if [ ! -n "$board" ]; then
        board="DFG-Networking-vNES Squad"
    fi
    python3 $trello_tool_path/main.py --config $trello_tool_path/auth.conf $board --include-members

}

# My changes (taken from bashrc)
function pogoda() {
    curl -H "Accept-Language: pl" wttr.in/$1
}

# On MacOS I need such workaround for pass to have working polish chars
function pass() {
    orig_ctype=$LC_CTYPE
    orig_lang=$LANG
    PASS=$(which -p pass)
    LC_CTYPE=C && LANG=C
    $PASS "$@"
    LC_CTYPE=$orig_ctype&& LANG=$orig_lang
}


alias pw="pogoda Wroclaw"

alias gemalto="pass -c Red-Hat/LinOTP---gemalto-token/GAKT000746B5"
alias freeotp="pass -c Red-Hat/LinOTP---soft-token/LSGO258325C1"
alias kerberos="pass -c Red-Hat/Kerberos/skaplons"

alias nmutt="stty discard undef; neomutt"

alias todo="todo.sh"

# Settings for fzf searching tool
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--height 40% --reverse --border'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
