###+++--- GPGConf ---+++###
utf8-strings
debug-level basic
log-file socket:///home/slaweq/.gnupg/log-socket
###+++--- GPGConf ---+++### czw, 19 maj 2022, 11:32:11 CEST
# GPGConf edited this configuration file.
# It will disable options before this marked block, but it will
# never change anything below these lines.
use-agent
pinentry-mode loopback