---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: centos:8
    privileged: true
    dockerfile: Dockerfile

  - name: centos7
    image: centos:7
    privileged: true
    dockerfile: Dockerfile

  - name: ubuntu
    image: ubuntu:bionic
    privileged: true
    dockerfile: Dockerfile

provisioner:
  name: ansible
  inventory:
    host_vars:
      centos7:
        ansible_user: root
      centos8:
        ansible_user: root
      ubuntu:
        ansible_user: root

verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
