---
- name: Install Centos 7/RHEL 7 development tools
  include_tasks: centos7.yml
  when: ((ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux') and
         ansible_distribution_version|int == 7)


- name: Install Centos 8/RHEL 8 development tools
  include_tasks: centos8.yml
  when: ((ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux') and
         ansible_distribution_version|int == 8)


- name: Install ubuntu development tools
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"


- name: Install packages from pypi
  become: yes
  become_method: sudo
  pip:
      name: ['pdbpp', 'remote_pdb', 'pbr', 'git-review']
      extra_args: --upgrade
