---
- name: Install Ubuntu dev packages
  package:
      name: ['python-dev', 'python3-dev', 'git-review', 'tox']
      state: present
  become: yes
  become_method: sudo
  when: ansible_distribution == "Ubuntu"


- name: Install Fedora dev packages
  package:
      name: ['python2-devel', 'python3-devel', 'git-review', 'tox']
      state: latest
  become: yes
  become_method: sudo
  when: ansible_distribution == "Fedora"


- name: Install Centos dev packages
  package:
      name: ['python-devel', 'python36-devel', 'git-review', 'gcc', 'gcc-c++',
             'make', 'openssl-devel', 'libcap-ng-devel', 'kernel-devel',
             'autoconf', 'automake', 'clang-devel', 'libtool', 'sparse',
             'sparse-devel', '@Development Tools']
      state: latest
  become: yes
  become_method: sudo
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'


- name: Install packages from pypi
  become: yes
  become_method: sudo
  pip:
      name: ['pdbpp', 'remote_pdb', 'pbr']
      extra_args: --upgrade
