---
- name: Include Centos 8/RHEL 8 tasks
  include_tasks: centos8.yml
  when: ((ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux') and
         ansible_distribution_version|int == 8)


- name: Install ansible package
  package:
      name: "ansible"
      state: latest
  become: yes
  become_method: sudo


- name: Install molecule package
  pip:
      name: "molecule"
      state: latest
  become: yes
  become_method: sudo


- name: "Check if podman is installed"
  package_facts:
    manager: "auto"


- name: Install molecule podman driver
  pip:
    name: ['molecule-podman']
  become: yes
  become_method: sudo
  when: "'podman' in ansible_facts.packages"


- name: Clone my ansible roles repo
  git:
    repo=https://github.com/slawqo/ansible
    version=master
    dest=/home/{{ ansible_user }}/ansible
  when: clone_roles == true
