- name: Install base i3wm packages
  become: yes
  become_method: sudo
  package:
      name: ["xsel", "feh", "rxvt-unicode", "urxvt-perls",
             "network-manager-applet", "arandr",
             "i3-gaps", "i3lock", "ranger", "xorg-xbacklight",
             "blueman", "dunst", "w3m", "pavucontrol",
             "zathura", "zathura-pdf-mupdf", "conky",
             "links", "xautolock", "lxappearance", "xorg-xinput",
             "alsa-utils", "pulsemixer"]
      state: present

- name: Install GTK engines
  become: yes
  become_method: sudo
  package:
    name: ["gtk-engine-murrine"]
    state: present
