- name: Install base i3wm packages
  become: yes
  become_method: sudo
  package:
      name: ["xsel", "feh", "rxvt-unicode", "urxvt-perls",
             "network-manager-applet", "i3-gaps", "i3lock",
             "blueman", "dunst", "w3m", "zathura", "zathura-pdf-mupdf",
             "conky", "links", "xautolock"]
      state: present

- name: Install GUI/Xorg packages
  become: yes
  become_method: sudo
  package:
    name: ["lxappearance", "xorg-xinput", "xorg-xbacklight", "arandr"]
    state: present

- name: Install audio packages
  become: yes
  become_method: sudo
  package:
    name: ["alsa-utils", "pamixer", "pasystray", "pavucontrol"]
    state: present

- name: Install GTK engines
  become: yes
  become_method: sudo
  package:
    name: ["gtk-engine-murrine", "arc-gtk-theme",
           "gtk-engines"]
    state: present

- name: Install file manager
  become: yes
  become_method: sudo
  package:
    name: ["ranger"]
    state: present

- name: Install Alacritty
  become: yes
  become_method: sudo
  package:
    name: ["alacritty"]
    state: present
