---
- name: Install base i3wm packages
  become: yes
  become_method: sudo
  package:
      name: ["xsel", "feh", "rxvt-unicode", "network-manager-applet",
             "i3", "i3lock", "ranger", "xbacklight", "blueman", "dunst",
             "volumeicon", "zathura", "zathura-pdf-mupdf", "conky",
             "links", "xautolock", "lxappearance"]
      state: present

- name: Install themes packages
  become: yes
  become_method: sudo
  package:
      name: ["breeze-icon-theme", "breeze-gtk",
             "numix-gtk-theme", "numix-icon-theme-circle",
             "numix-icon-theme-square",
             "glib2-devel", "gdk-pixbuf2-devel"]
      state: present

- name: Install Rofi themes
  become: yes
  become_method: sudo
  package:
      name: ["rofi-themes"]

