---

- name: Instal i3wm on Fedora
  include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Instal i3wm on Arch Linux
  include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"

- name: Install Thunar
  become: yes
  become_method: sudo
  package:
    name: ['thunar', 'gvfs']

- name: Install multimedia packages
  become: yes
  become_method: sudo
  package:
      name: ["mpv"]
      state: present

- name: Install Rofi
  become: yes
  become_method: sudo
  package:
      name: ["rofi"]

- name: Install Picom (composite manager)
  become: yes
  become_method: sudo
  package:
      name: ["picom"]

- name: Copy .Xresources file
  copy:
      src: 'files/Xresources'
      dest: '{{ ansible_env.HOME }}/.Xresources'

- name: Ensure i3wm config directory exists
  file:
      path: "{{ ansible_env.HOME }}/.config/i3"
      state: directory
      mode: 0755

- name: Copy i3wm config file
  template:
      src=i3_config.j2
      dest="{{ ansible_env.HOME }}/.config/i3/config"

- name: Copy i3lock script
  copy:
      src: 'files/i3wm/setbacklight.sh'
      dest: '{{ ansible_env.HOME }}/.config/i3/setbacklight.sh'
      mode: a+x

- name: Copy script to set screen backlight in i3
  copy:
      src: 'files/i3wm/setbacklight.sh'
      dest: '{{ ansible_env.HOME }}/.config/i3/setbacklight.sh'
      mode: a+x

- name: Copy script to set volume in i3
  copy:
      src: 'files/i3wm/setvolume.sh'
      dest: '{{ ansible_env.HOME }}/.config/i3/setvolume.sh'
      mode: a+x

- name: Copy script to set screens layout
  copy:
      src: 'files/i3wm/screens.sh'
      dest: '{{ ansible_env.HOME }}/.config/i3/screens.sh'
      mode: a+x

- name: Ensure screenlayouts directory exists
  file:
      path: "{{ ansible_env.HOME }}/.screenlayout"
      state: directory
      mode: 0755

- name: Copy only laptop screen layout
  copy:
      src: 'files/screenlayouts/only_laptop.sh'
      dest: '{{ ansible_env.HOME }}/.screenlayout/only_laptop.sh'
      mode: a+x

- name: Copy 3 external monitors screen layout
  copy:
      src: 'files/screenlayouts/3_external_monitors.sh'
      dest: '{{ ansible_env.HOME }}/.screenlayout/3_external_monitors.sh'
      mode: a+x

- name: Copy script to set screens layout
  copy:
      src: 'files/i3wm/screens.sh'
      dest: '{{ ansible_env.HOME }}/.config/i3/screens.sh'

- name: Ensure dunst config directory exists
  file:
      path: "{{ ansible_env.HOME }}/.config/dunst"
      state: directory
      mode: 0755

- name: Copy dunst config file
  copy:
      src: 'files/dunst/dunstrc'
      dest: '{{ ansible_env.HOME }}/.config/dunst/dunstrc'

- name: Copy conky config file
  copy:
      src: 'files/conky/conkyrc'
      dest: '{{ ansible_env.HOME }}/.conkyrc'

- name: Copy conky runner script
  copy:
      src: 'files/conky/run_conky.sh'
      dest: '{{ ansible_env.HOME }}/.run_conky.sh'
      mode: a+x

- name: Ensure ranger config directory exists
  file:
      path: "{{ ansible_env.HOME }}/.config/ranger"
      state: directory
      mode: 0755

- name: Copy ranger config file
  copy:
      src: 'files/ranger/rc.conf'
      dest: '{{ ansible_env.HOME }}/.config/ranger/rc.conf'

- name: Ensure rofi config directory exists
  file:
      path: "{{ ansible_env.HOME }}/.config/rofi"
      state: directory
      mode: 0755

- name: Copy rofi config file
  copy:
      src: 'files/rofi/config'
      dest: '{{ ansible_env.HOME }}/.config/rofi/config'

- name: Copy rofi web-search script
  copy:
      src: 'files/rofi/web-search.sh'
      dest: '{{ ansible_env.HOME }}/.config/rofi/web-search.sh'
      mode: a+x

- name: Ensure Alacritty config directory exists
  file:
      path: "{{ ansible_env.HOME }}/.config/alacritty"
      state: directory
      mode: 0755

- name: Copy rofi config file
  copy:
      src: 'files/alacritty/alacritty.yml'
      dest: '{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml'

- name: Ensure urxvt scripts directory exists
  become: yes
  become_method: sudo
  file:
      path: '/usr/lib64/urxvt/perl'
      state: directory
      mode: 0755

- name: Copy resize-font perl script for urxvt
  become: yes
  become_method: sudo
  copy:
      src: 'files/urxvt/resize-font'
      dest: '/usr/lib64/urxvt/perl/resize-font'

- name: Copy X11 brightness config file
  become: yes
  become_method: sudo
  copy:
      src: 'files/X11/10-backlight'
      dest: '/etc/X11/xorg.conf.d/10-backlight.conf'


- name: Ensure i3blocks config directory exists
  file:
      path: "{{ ansible_env.HOME }}/.config/i3blocks"
      state: directory
      mode: 0755

- name: Ensure i3blocks scripts directory exists
  file:
      path: "{{ ansible_env.HOME }}/.config/i3blocks/scripts"
      state: directory
      mode: 0755

- name: Copy i3blocks config file
  template:
      src=i3blocks_config.j2
      dest="{{ ansible_env.HOME }}/.config/i3blocks/config"

- name: Synchronize i3block scripts
  synchronize:
      src: "files/i3blocks/scripts/"
      dest: "{{ ansible_env.HOME }}/.config/i3blocks/scripts/"
      use_ssh_args: yes

- name: Copy picom config file
  copy:
      src: 'files/picom/picom.conf'
      dest: '{{ ansible_env.HOME }}/.config/picom.conf'
