---
- name: Install openvswitch package (Ubuntu)
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: true
  become: yes
  become_method: sudo
  with_items:
      - openvswitch-common
      - openvswitch-switch
  when: ansible_distribution == 'Ubuntu'


- name: Start openvswitch service on Ubuntu
  become: yes
  become_method: sudo
  service:
      name: "openvswitch-switch"
      state: started
  when: ansible_distribution == 'Ubuntu'


- name: Enable Centos repository
  become: yes
  become_method: sudo
  yum:
      name: centos-release-openstack-train
      state: present
  when: ansible_distribution == "CentOS"


- name: Install openvswitch package (CentOS)
  package:
      name: "openvswitch"
      state: latest
  become: yes
  become_method: sudo
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == "Fedora"


- name: Start openvswitch service on Centos or Fedora
  become: yes
  become_method: sudo
  service:
      name: "openvswitch"
      state: started
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == "Fedora"
