---
- name: Prepare hosts file
  become: yes
  become_method: sudo
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[inventory_hostname]['ansible_' + iface]['ipv4']['address'] }} {{ inventory_hostname }}"
    state: present
  when: iface is defined


- name: Configure private network interface
  become: yes
  become_method: sudo
  shell: "dhclient {{ private_iface }}"
  when: not(
        (private_iface is undefined) or
        (private_iface is none) or
        (private_iface | trim == ''))


- name: Enable IPv6
  become: yes
  become_method: sudo
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes


- name: Do Centos 7/RHEL 7 base configs
  include_tasks: centos7.yml
  when: ((ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux') and
         ansible_distribution_version|int == 7)


- name: Do Centos 8/RHEL 8 base configs
  include_tasks: centos8.yml
  when: ((ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux') and
         ansible_distribution_version|int == 8)


- name: Do Centos 9/RHEL 9 base configs
  include_tasks: centos9.yml
  when: ((ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux') and
         ansible_distribution_version|int == 9)


- name: Do Fedora base configs
  include_tasks: fedora.yaml
  when: ansible_distribution == "Fedora"


- name: Do ubuntu/debian base configs
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == 'Debian'


- name: Install new versions of setuptools
  become: yes
  become_method: sudo
  ignore_errors: true
  pip:
      name: "setuptools"
      extra_args: --upgrade


- name: Install new versions of wheel
  become: yes
  become_method: sudo
  ignore_errors: true
  pip:
      name: "wheel"
      extra_args: --upgrade


- name: Clone oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    version=master
    dest=/home/{{ ansible_user }}/.oh-my-zsh


- name: Clone zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    version=master
    dest=/home/{{ ansible_user }}/.zsh-autosuggestions


- name: Set zsh as base shell for {{ ansible_user }}
  become: yes
  become_method: sudo
  user:
      name={{ ansible_user }}
      shell="/bin/zsh"


- name: set timezone to Warsaw
  become: yes
  become_method: sudo
  timezone:
      name: Europe/Warsaw
