---
- name: Install libselinux-python bindings
  become: yes
  become_method: sudo
  package:
      name: libselinux-python
      state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'


- name: Install libselinux-python bindings on Fedora
  become: yes
  become_method: sudo
  package:
      name: ["python2-libselinux", "python3-libselinux"]
      state: present
  when: ansible_distribution == "Fedora"

- name: Prepare hosts file
  become: yes
  become_method: sudo
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[inventory_hostname]['ansible_' + iface]['ipv4']['address'] }} {{ inventory_hostname }}"
    state: present

- name: Configure private network interface
  become: yes
  become_method: sudo
  shell: "dhclient {{ private_iface }}"
  when: not(
        (private_iface is undefined) or
        (private_iface is none) or
        (private_iface | trim == ''))


- name: Add gf-release YUM repository
  become: yes
  become_method: sudo
  yum_repository:
    name: gf-release
    description: Repo with newer tmux version (>=2.1)
    baseurl: http://mirror.ghettoforge.org/distributions/gf/el/$releasever/plus/$basearch/
    gpgcheck: no
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'


- name: Add EPEL YUM repository
  become: yes
  become_method: sudo
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux Repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == "Fedora"


- name: Enable IPv6
  become: yes
  become_method: sudo
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 0
    sysctl_set: yes
    state: present
    reload: yes


- name: Install base packages
  package:
      name: "{{ item }}"
      state: latest
  become: yes
  become_method: sudo
  with_items:
      - htop
      - bmon
      - ccze
      - git
      - python-pip
      - rsync
      - zsh
      - tmux
      - dstat
      - stress
      - tig
      - telnet
      - tar


- name: Install Ubuntu specific packages
  package:
      name: "{{ item }}"
      state: latest
  become: yes
  become_method: sudo
  when: ansible_distribution == "Ubuntu"
  with_items:
      - exuberant-ctags
      - gettext
      - golang-go
      - unbound


- name: Install CentOS specific packages
  package:
      name: "{{ item }}"
      state: latest
  become: yes
  become_method: sudo
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == "Fedora"
  with_items:
      - vim-minimal
      - global-ctags
      - vim
      - go


- name: Install new versions of setuptools on Centos
  become: yes
  become_method: sudo
  pip:
      name: "setuptools"
      extra_args: --upgrade
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'


- name: Clone zprezto
  git:
    repo=https://github.com/slawqo/prezto.git
    version=master
    dest=/home/{{ ansible_user }}/.zprezto


- name: Set zsh as base shell for {{ ansible_user }}
  become: yes
  become_method: sudo
  user:
      name={{ ansible_user }}
      shell="/bin/zsh"


- name: set timezone to Warsaw
  become: yes
  become_method: sudo
  timezone:
      name: Europe/Warsaw
