---
- name: Install base packages
  package:
      name: ['htop', 'bmon', 'ccze', 'git', 'python3-pip', 'python-pip',
             'rsync', 'zsh', 'tmux', 'dstat', 'stress', 'tig', 'telnet', 'tar',
             'exuberant-ctags', 'gettext', 'golang-go', 'tzdata']
      state: latest
  become: yes
  become_method: sudo

