---
- name: Install base packages
  package:
      name: ['htop', 'bmon', 'ccze', 'git', 'python3-pip',
             'rsync', 'zsh', 'tmux', 'dstat', 'stress', 'tig', 'telnet', 'tar',
             'exuberant-ctags', 'gettext', 'golang-go', 'tzdata']
      state: latest
  become: yes
  become_method: sudo


- name: Install Ubuntu Bionic packages
  package:
      name: ["python-pip"]
      state: latest
  become: yes
  become_method: sudo
  when: ansible_distribution_version == "18.04"
