---
- name: Install Intel X11 driver
  become: yes
  become_method: sudo
  package:
    name: ["xf86-video-intel"]

- name: Install Desktop Manager
  become: yes
  become_method: sudo
  package:
    name: ["sddm"]

- name: Install Network Manager
  become: yes
  become_method: sudo
  package:
    name: ["networkmanager"]

- name: Install Libreoffice
  become: yes
  become_method: sudo
  package:
    name: ["libreoffice", "libreoffice-fresh-pl",
           "hunspell", "libmythes", "mythes-en",
           "mythes-pl"]
    state: present

- name: Install hplip for HP printers
  become: yes
  become_method: sudo
  package:
    name: "hplip"
    state: present

- name: Install pyqt5 (for hplip gui)
  become: yes
  become_method: sudo
  package:
    name: "python-pyqt5"
    state: present

- name: Install packages needed for printers
  become: yes
  become_method: sudo
  package:
      name: ["cups"]
      state: present

- name: Install packages needed for CPU fan control
  become: yes
  become_method: sudo
  package:
      name: ["thermald", "tlp"]
      state: present

- name: Ensure thermald is running
  become: yes
  become_method: sudo
  systemd:
    state: started
    enabled: yes
    name: thermald

- name: Ensure tlp is running
  become: yes
  become_method: sudo
  systemd:
    state: started
    enabled: yes
    name: tlp
