---
- name: Install base packages
  become: yes
  become_method: sudo
  package:
      name: ["vim", "tmux", "git", "weechat",
             "keepassxc", "rsync", "zsh", "glibc-langpack-pl",
             "NetworkManager", "htop", "bmon", "task", "timew",
             "python3-virtualenv", "jq",
             # Needed for BlueJeans app
             "GConf2"]
      state: present
  when: ansible_distribution == "Fedora"


- name: Install web browser
  become: yes
  become_method: sudo
  package:
    name: ['firefox']


- name: Install power management related packages
  become: yes
  become_method: sudo
  package:
      name: ["powertop", "lm_sensors"]
  when: ansible_distribution == "Fedora"


- name: Install development packages
  become: yes
  become_method: sudo
  package:
      name: ["@development-tools",
             "kernel-devel", "kernel-headers", "dkms",
             "qt5-qtx11extras", "elfutils-libelf-devel", "zlib-devel"]
      state: present
  when: ansible_distribution == "Fedora"


- name: Install Libreoffice
  become: yes
  become_method: sudo
  package:
      name: ["libreoffice"]
      state: present
  when: ansible_distribution == "Fedora"


- name: Install packages needed for printers
  become: yes
  become_method: sudo
  package:
      name: ["system-config-printer", "cups"]
  when: ansible_distribution == "Fedora"


- name: Clone oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    version=master
    dest=/home/{{ ansible_user }}/.oh-my-zsh


- name: Clone zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    version=master
    dest=/home/{{ ansible_user }}/.zsh-autosuggestions


- name: Set zsh as base shell for {{ ansible_user }}
  become: yes
  become_method: sudo
  user:
      name={{ ansible_user }}
      shell="/bin/zsh"
