---
- name: Install base packages
  become: yes
  become_method: sudo
  package:
      name: ["vim", "tmux", "git", "weechat",
             "keepassxc", "rsync", "zsh",
             "htop", "bmon", "task", "timew", "jq",]
      state: present


- name: Install web browser
  become: yes
  become_method: sudo
  package:
    name: ['firefox']


- name: Install power management related packages
  become: yes
  become_method: sudo
  package:
      name: ["powertop", "lm_sensors"]


- name: Install packages needed for printers
  become: yes
  become_method: sudo
  package:
      name: ["system-config-printer", "cups"]
  when: ansible_distribution == "Fedora"


- name: Install Vagrant on Fedora
  include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"


- name: Install Vagrant on Arch Linux
  include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"


- name: Clone oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    version=master
    dest=/home/{{ ansible_user }}/.oh-my-zsh


- name: Clone zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    version=master
    dest=/home/{{ ansible_user }}/.zsh-autosuggestions


- name: Set zsh as base shell for {{ ansible_user }}
  become: yes
  become_method: sudo
  user:
      name={{ ansible_user }}
      shell="/bin/zsh"

- name: Copy systemd power management file
  become: yes
  become_method: sudo
  copy:
      src: 'files/systemd/logind.conf'
      dest: '/etc/systemd/logind.conf'
