---
- name: Install base packages
  become: yes
  become_method: sudo
  package:
      name: ["vim", "tmux", "git", "weechat",
             "keepassxc", "rsync", "zsh", "glibc-langpack-pl",
             "NetworkManager", "htop", "bmon", "task", "timew",
             "python3-virtualenv", "jq",
             # Needed for BlueJeans app
             "GConf2"]
      state: present
  when: ansible_distribution == "Fedora"


- name: Install web browser
  become: yes
  become_method: sudo
  package:
    name: ['firefox']


- name: Install power management related packages
  become: yes
  become_method: sudo
  package:
      name: ["powertop", "lm_sensors"]
  when: ansible_distribution == "Fedora"


- name: Install development packages
  become: yes
  become_method: sudo
  package:
      name: ["@development-tools",
             "kernel-devel", "kernel-headers", "dkms",
             "qt5-qtx11extras", "elfutils-libelf-devel", "zlib-devel"]
      state: present
  when: ansible_distribution == "Fedora"


- name: Install Libreoffice
  become: yes
  become_method: sudo
  package:
      name: ["libreoffice"]
      state: present
  when: ansible_distribution == "Fedora"


- name: Install i3wm
  block:

  - name: Install base i3wm packages
    become: yes
    become_method: sudo
    package:
        name: ["xsel", "feh", "rxvt-unicode", "network-manager-applet",
               "i3lock", "ranger", "xbacklight", "blueman", "dunst",
               "volumeicon", "zathura", "zathura-pdf-mupdf", "conky",
               "links", "xautolock", "lxappearance"]
        state: present
    when: ansible_distribution == "Fedora"

  - name: Install Neomutt email client
    block:
      - name: enable copr repo
        command:
          cmd: dnf copr enable -y flatcap/neomutt
          creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:flatcap:neomutt.repo

      - name: Install neomutt package
        package:
          name: ['neomutt']
          state: present
    become: yes
    become_method: sudo

  - name: Install Thunar
    become: yes
    become_method: sudo
    package:
      name: ['thunar']

  - name: Install packages needed for printers
    become: yes
    become_method: sudo
    package:
        name: ["system-config-printer", "cups"]
    when: ansible_distribution == "Fedora"

  - name: Install themes packages
    become: yes
    become_method: sudo
    package:
        name: ["breeze-icon-theme", "breeze-gtk.x86_64",
               "numix-gtk-theme", "numix-icon-theme-circle",
               "numix-icon-theme-square",
               "glib2-devel", "gdk-pixbuf2-devel"]
        state: present
    when: ansible_distribution == "Fedora"

  - name: Install multimedia packages
    become: yes
    become_method: sudo
    package:
        name: ["mpv"]
        state: present
    when: ansible_distribution == "Fedora"

  - name: Install Rofi
    become: yes
    become_method: sudo
    package:
        name: ["rofi", "rofi-themes"]
    when: ansible_distribution == "Fedora"

  - name: "Check if offlineimap is installed"
    package_facts:
      manager: "auto"

  - name: Set offlineimap for RH mails in crontab
    cron:
      name: "check Red Hat mails"
      minute: "*/5"
      job: "timeout --kill-after=30s --signal=KILL 4m /usr/bin/offlineimap -o -a redhat"
    when: "'offlineimap' in ansible_facts.packages"

  - name: Set offlineimap for private mails in crontab
    cron:
      name: "check private mails"
      minute: "*/10"
      job: "timeout --kill-after=30s --signal=KILL 4m /usr/bin/offlineimap -o -a kaplonskipl"
    when: "'offlineimap' in ansible_facts.packages"
  when: desktop_type == 'i3'


- name: Clone oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    version=master
    dest=/home/{{ ansible_user }}/.oh-my-zsh


- name: Clone zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    version=master
    dest=/home/{{ ansible_user }}/.zsh-autosuggestions


- name: Set zsh as base shell for {{ ansible_user }}
  become: yes
  become_method: sudo
  user:
      name={{ ansible_user }}
      shell="/bin/zsh"
