---

- name: Copy .Xresources file
  copy:
      src: 'files/Xresources'
      dest: '{{ ansible_env.HOME }}/.Xresources'


- name: Ensure i3wm config directory exists
  file:
      path: "{{ ansible_env.HOME }}/.config/i3"
      state: directory
      mode: 0755


- name: Copy i3wm config file
  copy:
      src: 'files/i3wm/config'
      dest: '{{ ansible_env.HOME }}/.config/i3/config'
