galaxy_info:
  author: Slawek Kaplonski
  description: Install and configure AI tools (MCP servers, etc.)

  license: GPL-2.0-or-later

  min_ansible_version: 2.9

  galaxy_tags: []

dependencies: []
