"Better copy paste
set pastetoggle=<F2>
set clipboard=unnamed

filetype off
filetype plugin indent on
syntax on

set encoding=utf-8
set fileencodings=usc-bom,utf-8,latin2
set ts=4
set sts=4
set sw=4
set bs=2
set expandtab
set smartindent
set ruler
set number
set cursorline
set history=1000
set tw=80
set nowrap
set fo-=t
let &colorcolumn=join(range(81,999),",")
" Display status bar always
set laststatus=2

let mapleader = ","

"Służy do wygodniejszego poruszania się po okienkach.
"Zamiast wciskania CTRL+w, a później h/j/k/l, wciskasz sobie CTRL+h/j/k/l.:
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

"Wygodne przemieszczanie bloków kodu.
"Zaznaczasz tekst i wybierasz w którym kierunku ma być przesunięty.
" '<' (lewo), '>' (prawo).
vnoremap < <gv
vnoremap > >gv

"Highlight unwanted spaces at end of lines:
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
"Highlight column 80
highlight ColorColumn ctermbg=gray guibg=gray
set colorcolumn=80

if has('gui_running')
    colorscheme pychimp_mod
elseif &diff
    colorscheme pychimp_mod
else
    colorscheme pychimp_mod
endif

let g:pymode_rope = 0
let g:pymode_breakpoint = 0
let g:pymode_syntax = 1
let g:pymode_virtualenv = 1
let g:pymode_lint = 0
